In [1]:
import numpy as np
import random


In [10]:
input_list = [[0,0],[1,0],[0,1],[1,1]]

In [11]:
input_list = np.array(input_list)

In [17]:
label = []
for x in input_list:
    label.append(x[0] or x[1])

# インプットするデータと正解クラスのデータ表示

In [18]:
print(input_list)
print(label)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]
[0, 1, 1, 1]


# ステップ関数の定義

In [4]:
def step(X, T = 0.7):
    if X >= T:
        return 1
    else:
        return 0


# deltaの計算

In [43]:
def culc_delta(label, estimated, input_num, learning_rate=0.2): 
    return learning_rate*(label-estimated)*input_num
    

# weightの初期化

In [79]:
w1 = round(random.random(), 1)
w2 = round(random.random(), 1)

In [80]:
print(w1, w2)

0.4 0.2


In [81]:
weight_log = []
for y in range(10):
    for i,x in enumerate(input_list):
        X = x[0]*w1 + x[1]*w2
        result = step(X)
        delta_w1 = culc_delta(label[i], result, x[0])
        w1 += delta_w1
        delta_w2 = culc_delta(label[i], result, x[1])
        w2 += delta_w2
        weight_log.append([x[0], x[1],label[i], w1, w2,  result, delta_w1, delta_w2])

In [82]:
print(np.array(weight_log))

[[0.  0.  0.  0.4 0.2 0.  0.  0. ]
 [1.  0.  1.  0.6 0.2 0.  0.2 0. ]
 [0.  1.  1.  0.6 0.4 0.  0.  0.2]
 [1.  1.  1.  0.6 0.4 1.  0.  0. ]
 [0.  0.  0.  0.6 0.4 0.  0.  0. ]
 [1.  0.  1.  0.8 0.4 0.  0.2 0. ]
 [0.  1.  1.  0.8 0.6 0.  0.  0.2]
 [1.  1.  1.  0.8 0.6 1.  0.  0. ]
 [0.  0.  0.  0.8 0.6 0.  0.  0. ]
 [1.  0.  1.  0.8 0.6 1.  0.  0. ]
 [0.  1.  1.  0.8 0.8 0.  0.  0.2]
 [1.  1.  1.  0.8 0.8 1.  0.  0. ]
 [0.  0.  0.  0.8 0.8 0.  0.  0. ]
 [1.  0.  1.  0.8 0.8 1.  0.  0. ]
 [0.  1.  1.  0.8 0.8 1.  0.  0. ]
 [1.  1.  1.  0.8 0.8 1.  0.  0. ]
 [0.  0.  0.  0.8 0.8 0.  0.  0. ]
 [1.  0.  1.  0.8 0.8 1.  0.  0. ]
 [0.  1.  1.  0.8 0.8 1.  0.  0. ]
 [1.  1.  1.  0.8 0.8 1.  0.  0. ]
 [0.  0.  0.  0.8 0.8 0.  0.  0. ]
 [1.  0.  1.  0.8 0.8 1.  0.  0. ]
 [0.  1.  1.  0.8 0.8 1.  0.  0. ]
 [1.  1.  1.  0.8 0.8 1.  0.  0. ]
 [0.  0.  0.  0.8 0.8 0.  0.  0. ]
 [1.  0.  1.  0.8 0.8 1.  0.  0. ]
 [0.  1.  1.  0.8 0.8 1.  0.  0. ]
 [1.  1.  1.  0.8 0.8 1.  0.  0. ]
 [0.  0.  0.  0.8 0.

In [86]:
1 ^ 0

1