In [1]:
import tensorflow as tf

In [27]:
A = (tf.data.Dataset
    .range(1, 5, output_type=tf.int32)
    .map(lambda x: tf.fill([x], x)))

Cause: could not parse the source code:

    .map(lambda x: tf.fill([x], x)))

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: could not parse the source code:

    .map(lambda x: tf.fill([x], x)))

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [42]:
for element in C.as_numpy_iterator():
    print(element)

[3 3 3]
[1]
[2 2]
[4 4 4 4]


In [34]:
B = A.padded_batch(3, padded_shapes=5, padding_values=4444)

In [19]:
for element in B.as_numpy_iterator():
    print(element)

[[   1 4444 4444 4444 4444]
 [   2    2 4444 4444 4444]
 [   3    3    3 4444 4444]]
[[   4    4    4    4 4444]]
